#!/bin/bash

################################################################################
#
#  PS1 Customization
#
#     default suse PS1: "$(ppwd \l)\u@\h:\w> "
#
################################################################################

#    Colors used in the PS1
#      customization
#
#######################################
# No Color
PS_NC='\[\e[0m\]'
# Normal Weight
PS_BLACK='\[\e[0;30m\]'
PS_RED='\[\e[0;31m\]'
PS_GREEN='\[\e[0;32m\]'
PS_BROWN='\[\e[0;33m\]'
PS_BLUE='\[\e[0;34m\]'
PS_PURPLE='\[\e[0;35m\]'
PS_CYAN='\[\e[0;36m\]'
PS_LIGHTGRAY='\[\e[0;37m\]'
# Bold Colors
PS_DARKGRAY='\[\e[1;30m\]'
PS_LIGHTRED='\[\e[1;31m\]'
PS_LIGHTGREEN='\[\e[1;32m\]'
PS_YELLOW='\[\e[1;33m\]'
PS_LIGHTBLUE='\[\e[1;34m\]'
PS_LIGHTPURPLE='\[\e[1;35m\]'
PS_LIGHTCYAN='\[\e[1;36m\]'
PS_WHITE='\[\e[1;37m\]'

MAIN=$PS_GREEN
OFF=$PS_CYAN

PS1="$MAIN\h:$OFF \w$MAIN>$PS_NC "

